"""limpieza de campos y agregado de clasificador

Revision ID: 05904f40240c
Revises: 507bd8daddb1
Create Date: 2026-02-19 13:41:40.771367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05904f40240c'
down_revision = '507bd8daddb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_proceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=False),
    sa.Column('codigo_clasificador', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('v_unitario', sa.Float(), nullable=True),
    sa.Column('v_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos_contractuales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_proceso')
    # ### end Alembic commands ###
