"""Agregando campo promedio

Revision ID: 065cac622c3c
Revises: 11e24e66b337
Create Date: 2026-03-04 13:22:53.750477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065cac622c3c'
down_revision = '11e24e66b337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promedio_propuestas', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_column('promedio_propuestas')

    # ### end Alembic commands ###
