"""Agregando campos de propuestas y fecha recibido

Revision ID: 11c91e14d00c
Revises: 9730d7edabe1
Create Date: 2026-03-03 16:09:05.222902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c91e14d00c'
down_revision = '9730d7edabe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_propuesta2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_propuesta3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('f_recibido', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_column('f_recibido')
        batch_op.drop_column('valor_propuesta3')
        batch_op.drop_column('valor_propuesta2')

    # ### end Alembic commands ###
