"""eliminado el campo de rubro

Revision ID: 11e24e66b337
Revises: 548749d1d7a7
Create Date: 2026-03-04 12:07:07.898365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e24e66b337'
down_revision = '548749d1d7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_column('rubro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubro', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
