"""nuevo campo link

Revision ID: 2204a01b8b70
Revises: dec7667707bd
Create Date: 2026-04-03 08:05:24.574303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2204a01b8b70'
down_revision = 'dec7667707bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_secop', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_column('link_secop')

    # ### end Alembic commands ###
