"""Eliminar columnas obsoletas de procesos

Revision ID: 299c94b3558d
Revises: 05904f40240c
Create Date: 2026-02-19 17:40:06.459164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299c94b3558d'
down_revision = '05904f40240c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_column('cod_clase')
        batch_op.drop_column('cod_producto')
        batch_op.drop_column('cod_segmento')
        batch_op.drop_column('cod_familia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_familia', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cod_segmento', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cod_producto', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cod_clase', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
