"""crear tablas procesos contractuales corregido

Revision ID: 507bd8daddb1
Revises: 79a2f0c2d21e
Create Date: 2026-02-15 15:26:50.834189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507bd8daddb1'
down_revision = '79a2f0c2d21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procesos_contractuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vigencia', sa.Integer(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=100), nullable=True),
    sa.Column('objeto_desc', sa.Text(), nullable=True),
    sa.Column('f_elaboracion', sa.Date(), nullable=True),
    sa.Column('f_publicacion', sa.Date(), nullable=True),
    sa.Column('f_recepcion', sa.Date(), nullable=True),
    sa.Column('f_cierre', sa.Date(), nullable=True),
    sa.Column('f_verificacion', sa.Date(), nullable=True),
    sa.Column('f_firma', sa.Date(), nullable=True),
    sa.Column('plazo_txt', sa.String(length=200), nullable=True),
    sa.Column('cod_segmento', sa.String(length=50), nullable=True),
    sa.Column('cod_familia', sa.String(length=50), nullable=True),
    sa.Column('cod_clase', sa.String(length=50), nullable=True),
    sa.Column('cod_producto', sa.String(length=50), nullable=True),
    sa.Column('cdp_numero', sa.String(length=100), nullable=True),
    sa.Column('cod_presupuestal', sa.String(length=100), nullable=True),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procesos_contractuales')
    # ### end Alembic commands ###
