"""Agregando campo rubro

Revision ID: 548749d1d7a7
Revises: 11c91e14d00c
Create Date: 2026-03-04 11:57:20.459247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548749d1d7a7'
down_revision = '11c91e14d00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubro', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_column('rubro')

    # ### end Alembic commands ###
