"""correcion columna nombre_completo usuarios

Revision ID: 6d09b3c3bcd1
Revises: 73baaac04bda
Create Date: 2026-03-14 14:14:13.727509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d09b3c3bcd1'
down_revision = '73baaac04bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_completo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('nombre_completo')

    # ### end Alembic commands ###
