"""cambios para eliminacion en cascada de colegios

Revision ID: 73baaac04bda
Revises: 
Create Date: 2026-03-14 00:23:46.928439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73baaac04bda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('procesos_contractuales_colegio_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('procesos_contractuales_colegio_id_fkey'), 'colegios', ['colegio_id'], ['id'])

    # ### end Alembic commands ###
