"""Agregados proveedores adicionales

Revision ID: 76db2590a3d9
Revises: f110e291211c
Create Date: 2026-02-27 15:11:12.163866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76db2590a3d9'
down_revision = 'f110e291211c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_proceso', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'procesos_contractuales', ['proceso_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.alter_column('vigencia',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               nullable=True)
        batch_op.alter_column('cdp_numero',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('procesos_contractuales_colegio_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'colegios', ['colegio_id'], ['id'])
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('procesos_contractuales_colegio_id_fkey'), 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('cdp_numero',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('vigencia',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('items_proceso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
