"""crear tabla intermedia colegio proveedor

Revision ID: 79a2f0c2d21e
Revises: aa06dec513c9
Create Date: 2026-02-11 00:16:51.497352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a2f0c2d21e'
down_revision = 'aa06dec513c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colegio_proveedor',
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('colegio_id', 'proveedor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colegio_proveedor')
    # ### end Alembic commands ###
