"""nuevos campos de contacto para los usuarios

Revision ID: 7be1d0cba976
Revises: 92ad931ca1e6
Create Date: 2026-03-12 11:09:28.053167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be1d0cba976'
down_revision = '92ad931ca1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('telefono')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
