"""Relaciones entre usuario, proveedores y colegios

Revision ID: 8e59e8dc1c54
Revises: 7be1d0cba976
Create Date: 2026-03-12 12:31:24.003861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e59e8dc1c54'
down_revision = '7be1d0cba976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('proveedores_documento_key'), type_='unique')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('proveedores_documento_key'), ['documento'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
