"""Refactor tabla proveedores

Revision ID: 97659d2b9f28
Revises: 6d09b3c3bcd1
Create Date: 2026-03-16 07:02:16.511414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97659d2b9f28'
down_revision = '6d09b3c3bcd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_proveedores_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_proveedores_documento'))
        batch_op.create_index(batch_op.f('ix_proveedores_documento'), ['documento'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_documento'))
        batch_op.create_index(batch_op.f('ix_proveedores_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedores_usuario_id'), ['usuario_id'], unique=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
