"""Blindaje de rendimiento con indices

Revision ID: 97d40c8465d3
Revises: a57162a23d19
Create Date: 2026-03-12 13:14:12.338796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d40c8465d3'
down_revision = 'a57162a23d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('colegios_nit_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_colegios_nit'), ['nit'], unique=True)
        batch_op.create_index(batch_op.f('ix_colegios_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedores_documento'), ['documento'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedores_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_proveedores_documento'))

    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colegios_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_colegios_nit'))
        batch_op.create_unique_constraint(batch_op.f('colegios_nit_key'), ['nit'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
