"""Crear tabla proveedores con datos contables

Revision ID: aa06dec513c9
Revises: 
Create Date: 2026-02-10 15:51:40.367460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa06dec513c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_tercero', sa.String(length=50), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('dv', sa.String(length=1), nullable=True),
    sa.Column('renta', sa.String(length=50), nullable=True),
    sa.Column('primer_nombre', sa.String(length=100), nullable=True),
    sa.Column('segundo_nombre', sa.String(length=100), nullable=True),
    sa.Column('primer_apellido', sa.String(length=100), nullable=True),
    sa.Column('segundo_apellido', sa.String(length=100), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('movil', sa.String(length=50), nullable=True),
    sa.Column('correo_electronico', sa.String(length=150), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('no_cuenta', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    op.drop_table('proveedores')
    # ### end Alembic commands ###
