"""Optimizacion de indices y relaciones historial

Revision ID: adfbdd113d52
Revises: 97659d2b9f28
Create Date: 2026-03-16 09:39:25.599458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfbdd113d52'
down_revision = '97659d2b9f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_proceso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_proceso_proceso_id'), ['proceso_id'], unique=False)

    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procesos_contractuales_colegio_id'), ['colegio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procesos_contractuales_proveedor2_id'), ['proveedor2_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procesos_contractuales_proveedor3_id'), ['proveedor3_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procesos_contractuales_proveedor_id'), ['proveedor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procesos_contractuales_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_procesos_contractuales_proveedor3_id'))
        batch_op.drop_index(batch_op.f('ix_procesos_contractuales_proveedor2_id'))
        batch_op.drop_index(batch_op.f('ix_procesos_contractuales_colegio_id'))

    with op.batch_alter_table('items_proceso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_proceso_proceso_id'))

    # ### end Alembic commands ###
