"""Agregar nueva columna rubro

Revision ID: b3173af5f385
Revises: bf1a493dd7f2
Create Date: 2026-03-04 16:56:48.918342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3173af5f385'
down_revision = 'bf1a493dd7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubro_nombre', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_column('rubro_nombre')

    # ### end Alembic commands ###
