"""Agregar columna gran_total

Revision ID: bf1a493dd7f2
Revises: 065cac622c3c
Create Date: 2026-03-04 14:11:04.273005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1a493dd7f2'
down_revision = '065cac622c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gran_total', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_column('gran_total')

    # ### end Alembic commands ###
