"""cambio campo rector_tipo_documento

Revision ID: dec7667707bd
Revises: adfbdd113d52
Create Date: 2026-03-20 14:04:54.858537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec7667707bd'
down_revision = 'adfbdd113d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.alter_column('rector_tipo_documento',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'CC'::doc_type"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colegios', schema=None) as batch_op:
        batch_op.alter_column('rector_tipo_documento',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False,
               existing_server_default=sa.text("'CC'::doc_type"))

    # ### end Alembic commands ###
