"""crear nuevo campo para contar procesos

Revision ID: eeeaca89176e
Revises: b3173af5f385
Create Date: 2026-03-06 12:37:28.292757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeeaca89176e'
down_revision = 'b3173af5f385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_proceso_colegio', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.drop_column('numero_proceso_colegio')

    # ### end Alembic commands ###
