"""Mas caracteres para los links

Revision ID: ef7786832f79
Revises: 2204a01b8b70
Create Date: 2026-04-03 14:34:37.503102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7786832f79'
down_revision = '2204a01b8b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.alter_column('link_secop',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos_contractuales', schema=None) as batch_op:
        batch_op.alter_column('link_secop',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
