"""Nuevos campos para la eliminacion en cascada de los  colegios

Revision ID: f79b3d1ccca6
Revises: 97d40c8465d3
Create Date: 2026-03-13 12:57:14.183560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79b3d1ccca6'
down_revision = '97d40c8465d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colegio_proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('colegio_proveedor_colegio_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('colegio_proveedor_proveedor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'colegios', ['colegio_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'proveedores', ['proveedor_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colegio_proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('colegio_proveedor_proveedor_id_fkey'), 'proveedores', ['proveedor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('colegio_proveedor_colegio_id_fkey'), 'colegios', ['colegio_id'], ['id'])

    # ### end Alembic commands ###
